version: '3.8'

services:
  prefect-orion:
    build: .
    ports:
      - "4200:4200"
    volumes:
      - ./data:/data
    environment:
      - PREFECT_ORION_DATABASE_CONNECTION_URL=sqlite:///root/.prefect/orion.db
    command: prefect orion start --host 0.0.0.0
